######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 4 13:51:49 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += inputmethod.h keyboard.h login.h ui_keyboard.h
SOURCES += inputmethod.cpp keyboard.cpp login.cpp main.cpp
RESOURCES += keypad.qrc
target.path = /home/asd
INSTALLS += target
